### ISSUE TITLE
Fix for Yahoo: Failed to verify assertion (message: No OpenID provider was discovered for the asserted claimed identifier)

### ISSUE THREAD

**Issue by therontock** [jaredhanson/passport-yahoo#6]
Starting about a week ago passport-yahoo started breaking.  I finally tracked down the issue to a change that Yahoo made that is exposed by code in openid.js.  Perhaps this is fixed with the latest version of the openid code but I'm running with a frozen set of npm modules.  I am posting in the hopes this saves someone else the multiple hours it took me to track this down, even though the author appears to have abandoned this project.

The change Yahoo made is that this command:
  `curl -H 'Accept: application/xrds+xml,text/html,text/plain,*/*' https://me.yahoo.com/.well-known/host-meta`

now returns different data.  There is some content-type problem on Yahoo's side, because if you remove '*/*' from the list (or 'text/html') then the correct content is returned -- even though the returned content-type remains the same.

To fix the problem, run this command to remove the '*/*' from the Accept header that is sent:
  `sed -i 's%,\*/\*%%' node_modules/passport-yahoo/node_modules/passport-openid/node_modules/openid/openid.js`

**Comment by AGT89** [comment]
I'm having the same issue and getting the error message "InternalOpenIDError: Failed to discover OP endpoint URL"

This is reproducible using the signon example from this repo:

1. Download the signon example.
2. Change express version dependency to 2.5.10 in package.json.
3. npm install
4. node app.js
5. Go to http://localhost:3000/login and click "Sign On with Yahoo"

Opened havard/node-openid#163 as the issue is in openid.js

**Comment by jbruggem** [comment]
It's now fixed in node-openid. Just needs a bump in this package.json !

**Comment by Martii** [comment]
Just doing some follow up here... we've successfully tested AOL passport... and are awaiting Yahoo verification testing... thanks for everyone who did post something. :)

Refs:
*passport-openid* is also affected and *passport-aol* ... *passport-openid* is what sub-depends using *openid* a.k.a. [node-openid](https://github.com/havard/node-openid) here on GH vs [npmjs.com](https://www.npmjs.com/package/openid).

**Comment by jack2ky** [comment]
Is the yahoo passport strategy fixed?

**Comment by montykamath** [comment]
I'm still getting this error: 'No OpenID provider was discovered for the asserted claimed identifier'.  Is there a fix?

**Comment by jyoti007** [comment]
I am facing the same issue, Have anyone find any solution.
